name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [seeeduino_xiao_ble]
        shield: [square_macro]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
        


      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build python3-pip
          pip3 install --user west
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Initialize west and update modules
        run: |
          west init -l
          west update
          west zephyr-export
          pip3 install -r zephyr/scripts/requirements.txt

      - name: Build firmware
        run: |
          west build -s zmk/app -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }}

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/zmk.uf2

      - name: Check if .west directory exists
        id: check_west
        run: |
          if [ -d ".west" ]; then
            echo "West already initialized, skipping init."
            echo "skip_west=true" >> $GITHUB_ENV
          else
            echo "Initializing west..."
            west init -l
          fi

      # west init -l をスキップする場合
      - name: Run west command only if not initialized
        if: env.skip_west != 'true'
        run: west update
   
